# Generated by Django 3.1.6 on 2021-02-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nume', models.CharField(max_length=30)),
                ('Prenume', models.CharField(max_length=30)),
                ('Telefon', models.IntegerField()),
                ('Email', models.EmailField(max_length=35, null=True)),
            ],
            options={
                'ordering': ['Nume', 'Prenume'],
            },
        ),
        migrations.CreateModel(
            name='Destinatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nume_Destinatie', models.CharField(max_length=30)),
                ('Oras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Responsabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nume_Responsabil', models.CharField(max_length=30)),
                ('Prenume_Responsabil', models.CharField(max_length=30)),
                ('Telefon_Responsabil', models.IntegerField()),
                ('Email_Responsabil', models.EmailField(max_length=35, null=True)),
                ('Salariu', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tip_Transport', models.CharField(max_length=20)),
                ('Destinatie', models.ManyToManyField(to='agentie.Destinatie')),
            ],
        ),
        migrations.CreateModel(
            name='Pachet_Turistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tip_Pachet', models.CharField(max_length=30)),
                ('Zi_inceput', models.DateField(auto_now_add=True)),
                ('Zi_sfarsit', models.DateField()),
                ('Client', models.ManyToManyField(to='agentie.Client')),
                ('Destinatie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentie.destinatie')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nume_Hotel', models.CharField(max_length=20)),
                ('Pret_noapte', models.IntegerField()),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Nr_Camere', models.IntegerField()),
                ('Destinatie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentie.destinatie')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Responsabil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentie.responsabil'),
        ),
    ]
