# Generated by Django 3.1.6 on 2021-02-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentie', '0003_auto_20210221_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Parola',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
