# Generated by Django 3.1.6 on 2021-02-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentie', '0004_client_parola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Parola',
            field=models.CharField(max_length=30),
        ),
    ]
