# Generated by Django 3.1.6 on 2021-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentie', '0005_auto_20210222_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Parola',
        ),
        migrations.AlterField(
            model_name='client',
            name='Telefon',
            field=models.IntegerField(null=True),
        ),
    ]
