# Generated by Django 3.1.6 on 2021-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentie', '0006_auto_20210223_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.EmailField(max_length=35),
        ),
        migrations.AlterField(
            model_name='client',
            name='Telefon',
            field=models.IntegerField(),
        ),
    ]
