# Generated by Django 3.1.6 on 2021-02-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentie', '0007_auto_20210223_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Responsabil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentie.responsabil'),
        ),
    ]
