# Generated by Django 3.1.6 on 2021-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentie', '0012_auto_20210223_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Pachet_Turistic',
        ),
        migrations.AddField(
            model_name='hotel',
            name='Pachet_Turistic',
            field=models.ManyToManyField(null=True, to='agentie.Pachet_Turistic'),
        ),
    ]
