# Generated by Django 3.1.6 on 2021-02-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentie', '0014_auto_20210223_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Pachet_Turistic',
        ),
        migrations.AddField(
            model_name='pachet_turistic',
            name='Destinatie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentie.destinatie'),
        ),
    ]
